# Generated by Django 4.2 on 2023-08-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="waiting_verified",
            field=models.BooleanField(default=False),
        ),
    ]
