# Generated by Django 4.2 on 2023-08-31 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_worker_waiting_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="waiting_verified",
        ),
    ]
