# Generated by Django 4.2 on 2023-08-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_remove_worker_waiting_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="waiting_verified",
            field=models.BooleanField(default=False),
        ),
    ]
