# Generated by Django 4.2 on 2023-09-10 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_worker_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={
                "ordering": ["position"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
